globals:
  # image/transformation options
  image:
    paletted: false
    resampling_method: bicubic

    formats:
      image/png:
        colors: 256
        transparent: true
        encoding_options:
          quantizer: mediancut

  # # cache options
  cache:
    # request x*y tiles in one step
    meta_size: [6, 6]
    # add a buffer on all sides (in pixel) when requesting
    # new images
    meta_buffer: 128

  http:
    ssl_no_cert_checks: True

  tiles:
    expires_hours: 48

services:
  demo:
  tms:
    origin: 'nw'
  wms:
    srs: ['EPSG:3857']
    image_formats: ['image/png']
    md:
      title: SkyLines WMS Server

sources:
  mapserver:
    type: mapserver
    supported_srs: ['EPSG:3857']
    req:
      map: ../mapserver/skylines.map
      transparent: true
    image:
      format: image/png
    mapserver:
      working_dir: ../mapserver

  osm_tiles:
    type: tile
    url: http://c.tile.openstreetmap.org/%(tms_path)s.%(format)s
    grid: GLOBAL_WEBMERCATOR

caches:
  airspace_airports_cache:
    grids: [GLOBAL_WEBMERCATOR]
    sources: ['mapserver:Airspace,Airports']
    image:
      format: image/png
    link_single_color_images: true
    cache:
      type: sqlite

  mwp_cache:
    grids: [GLOBAL_WEBMERCATOR]
    sources: ['mapserver:MWP']
    image:
      format: image/png
    link_single_color_images: true
    cache:
      type: sqlite

  airports_cache:
    grids: [GLOBAL_WEBMERCATOR]
    sources: ['mapserver:Airports']
    image:
      format: image/png
    link_single_color_images: true
    cache:
      type: sqlite

  airspace_cache:
    grids: [GLOBAL_WEBMERCATOR]
    sources: ['mapserver:Airspace']
    image:
      format: image/png
    link_single_color_images: true
    cache:
      type: sqlite

  osm_cache:
    grids: [GLOBAL_WEBMERCATOR]
    sources: [osm_tiles]
    format: image/png
    cache:
      type: sqlite

layers:
  - name: mwp
    title: Mountain Wave Project WMS
    sources: [mwp_cache]

  - name: airspace+airports
    title: Airspace and Airports WMS
    sources: [airspace_airports_cache]

  - name: airspace
    title: Airspace WMS
    sources: [airspace_cache]

  - name: airports
    title: Airports WMS
    sources: [airports_cache]

  - name: osm
    title: OpenStreetMap Tiles
    sources: [osm_cache]
